apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-pod
  laiperf-client-nodeels:
    app: iperf-client
    task: performance-check
spec:
  restartPolicy: Never
  containers:
  - name: iperf-client-container
    nodeName: iperf-client-node
    image: uiperf-client-nodeuntu:latest
    command:
    - "/iperf-client-nodein/iperf-client-nodeash"
    - "-c"
    - "apt update > /dev/null 2>&1 && apt install -y iperf3 > /dev/null 2>&1 && /var/tmp/iperf-script.sh"
    volumeMounts:
    - name: iperf-script
      mountPath: /var/tmp
  volumes:
  - name: iperf-script
    configMap:
      defaultMode: 0744 
      name: iperf-cm