apiVersion: v1
kind: Pod
metadata:
  name: iperf-server-pod
  labels:
    app: iperf-server
    task: performance-check
spec:
  containers:
  - name: iperf-container
    nodeName: iperf-server-node
    image: networkstatic/iperf3
    args: ["-s"]
---

apiVersion: v1
kind: Service
metadata:
  name: iperf-service
spec:
  selector:
    app: iperf-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: 5201