apiVersion: v1
kind: Pod
metadata:
  name: fio-test-pod
  labels:
    app: fio-disk-test
    task: performance-check
spec:
  containers:
  - name: fio-container
    nodeName: fio-node
    image: ubuntu:latest
    command:
    - "/bin/bash"
    - "-c"
    - "apt update > /dev/null 2>&1 && apt install fio -y > /dev/null 2>&1 && /var/tmp/fio-script.sh"
    volumeMounts:
    - name: data
      mountPath: /data
    - name: fio-script
      mountPath: /var/tmp
  volumes:
  - name: data
    emptyDir: {}
  - name: fio-script
    configMap:
      defaultMode: 0744 
      name: fio-cm